repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.9
        args: [--line-length=120]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]
        args: [--max-line-length=120, --ignore=E203,W503,E402,F401]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=120"]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]

ci:
  autofix_commit_msg: "style: [pre-commit.ci] auto fixes from pre-commit.com hooks"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autofix_prs: true
  autoupdate_schedule: weekly
