version: '3.8'

services:
  api:
    build:
      context: ./apps/sheily_light_api
      dockerfile: Dockerfile
    container_name: sheily_api
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - db
      - ollama

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: sheily_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api

  db:
    image: postgres:13
    container_name: sheily_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sheily
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sheily
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sheily"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: sheily_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data:
